-- Auto-generated by tools/generate-stop-translations.mjs
-- Applies localized stop names by stop_code (GTFS stop_id for this feed).

BEGIN;

UPDATE bus_stops AS bs
SET
  name_kk = v.name_kk,
  name_ru = v.name_ru,
  name_en = v.name_en,
  updated_at = NOW()
FROM (
  SELECT '69d3a2a0-c1c5-4c40-9930-6f7f2fa2ae2a'::text AS stop_code, 'Kafe Sulukol'''::text AS name_kk, 'Кафе Сулукол'::text AS name_ru, 'Kafe Sulukol'''::text AS name_en UNION ALL
  SELECT '18e751ea-9e23-49dd-9275-4559c1ed40b0'::text AS stop_code, 'Shugyla'::text AS name_kk, 'шугыла'::text AS name_ru, 'Shugyla'::text AS name_en UNION ALL
  SELECT '77be7d79-bc6c-4c3d-a629-42529171f5da'::text AS stop_code, 'Kladbishche'::text AS name_kk, 'Кладбище'::text AS name_ru, 'Kladbishche'::text AS name_en UNION ALL
  SELECT '439de39e-eed6-49be-9fc7-e232cc3c3f84'::text AS stop_code, 'Medeu'::text AS name_kk, 'Медеу'::text AS name_ru, 'Medeu'::text AS name_en UNION ALL
  SELECT 'cb356626-5f8b-4acd-82b4-d01a06d43b3f'::text AS stop_code, 'K''artaly'::text AS name_kk, 'Карталы'::text AS name_ru, 'K''artaly'::text AS name_en UNION ALL
  SELECT '49f207a4-a4d2-44ee-983a-8f330bf0375c'::text AS stop_code, 'Akan Sery'::text AS name_kk, 'Акан Серы'::text AS name_ru, 'Akan Sery'::text AS name_en UNION ALL
  SELECT '3a8b16e7-e35d-4891-99dc-179197ec2b6e'::text AS stop_code, 'prospekt Tlendieva'::text AS name_kk, 'проспект Тлендиева'::text AS name_ru, 'prospekt Tlendieva'::text AS name_en UNION ALL
  SELECT '6c7bf549-6c5b-4078-bfbf-22027216c209'::text AS stop_code, 'Sarybulak'::text AS name_kk, 'Сарыбулак'::text AS name_ru, 'Sarybulak'::text AS name_en UNION ALL
  SELECT '20608557-4a9c-433d-89cb-c0dd527618d3'::text AS stop_code, 'Sredniaia shkola No. 18'::text AS name_kk, 'Средниаиа школа № 18'::text AS name_ru, 'Sredniaia shkola No. 18'::text AS name_en UNION ALL
  SELECT '6315f075-d165-40b9-b97c-aa60a49512d0'::text AS stop_code, 'ZhK Svechki'::text AS name_kk, 'ЖК Свечки'::text AS name_ru, 'ZhK Svechki'::text AS name_en UNION ALL
  SELECT 'd124d339-88ed-42e4-8593-838cbad37811'::text AS stop_code, 'Teatr Astana Opera'::text AS name_kk, 'Театр Астана Опера'::text AS name_ru, 'Teatr Astana Opera'::text AS name_en UNION ALL
  SELECT 'a10b4fa3-0b47-4297-b29b-4d16b670ca00'::text AS stop_code, 'TRTs Khan Shatyr'::text AS name_kk, 'ТРЦ хан шатыр'::text AS name_ru, 'TRTs Khan Shatyr'::text AS name_en UNION ALL
  SELECT '33611474-3457-4f2a-919d-82064f2d8e54'::text AS stop_code, 'Respublikanskii diagnosticheskii tsentr'::text AS name_kk, 'Республиканскии диагностическии центр'::text AS name_ru, 'Respublikanskii diagnosticheskii tsentr'::text AS name_en UNION ALL
  SELECT '870084cf-ed0b-4bbd-bea0-368b5bce2425'::text AS stop_code, 'Kardiokhirurgicheskaia klinika'::text AS name_kk, 'Кардиохирургическаиа клиника'::text AS name_ru, 'Kardiokhirurgicheskaia klinika'::text AS name_en UNION ALL
  SELECT '2dc158f2-0a35-4643-9ac2-4cc3fa09036a'::text AS stop_code, 'Mechet'' Abu Nasyr al-Farabi'::text AS name_kk, 'Мечет Абу Насыр ал-Фараби'::text AS name_ru, 'Mechet'' Abu Nasyr al-Farabi'::text AS name_en UNION ALL
  SELECT 'a7c336fd-6ada-4818-a1c2-ae38f89d9d64'::text AS stop_code, 'TRTs Keruen'::text AS name_kk, 'ТРЦ Керуен'::text AS name_ru, 'TRTs Keruen'::text AS name_en UNION ALL
  SELECT '8eb3db61-5a0c-420d-80cf-f2b44eb9676a'::text AS stop_code, 'ZhK Orynbor Towers'::text AS name_kk, 'ЖК Орынбор Товерс'::text AS name_ru, 'ZhK Orynbor Towers'::text AS name_en UNION ALL
  SELECT '5d11962d-6412-4c7c-984d-f4ee5eb63859'::text AS stop_code, 'Karakat'::text AS name_kk, 'Каракат'::text AS name_ru, 'Karakat'::text AS name_en UNION ALL
  SELECT '3db7fef2-0573-4884-af46-8d0986364f93'::text AS stop_code, 'Zharkyn'::text AS name_kk, 'жаркын'::text AS name_ru, 'Zharkyn'::text AS name_en UNION ALL
  SELECT 'bffe93af-d0f5-4216-84e9-55893d7beefd'::text AS stop_code, 'ZhK Komfort taun'::text AS name_kk, 'ЖК Комфорт таун'::text AS name_ru, 'ZhK Komfort taun'::text AS name_en UNION ALL
  SELECT '339fa8e4-18ae-4cfa-b6e9-111e97207174'::text AS stop_code, 'ZhK Komfort taun'::text AS name_kk, 'ЖК Комфорт таун'::text AS name_ru, 'ZhK Komfort taun'::text AS name_en UNION ALL
  SELECT '13d3a76f-5cc8-4d6f-8b5a-335beea7eb5c'::text AS stop_code, 'ZhK Nova city'::text AS name_kk, 'ЖК Нова киты'::text AS name_ru, 'ZhK Nova city'::text AS name_en UNION ALL
  SELECT '188e1c69-e5de-4a89-abf0-b1bd3e0880cc'::text AS stop_code, 'Zharkyn'::text AS name_kk, 'жаркын'::text AS name_ru, 'Zharkyn'::text AS name_en UNION ALL
  SELECT 'ee853e2c-e631-45a9-8f2d-be48c4c9da88'::text AS stop_code, 'Karakat'::text AS name_kk, 'Каракат'::text AS name_ru, 'Karakat'::text AS name_en UNION ALL
  SELECT 'd341a88a-9c13-4e35-9a89-10090402b94c'::text AS stop_code, 'ZhK Orynbor Towers'::text AS name_kk, 'ЖК Орынбор Товерс'::text AS name_ru, 'ZhK Orynbor Towers'::text AS name_en UNION ALL
  SELECT '0241ba8f-1c7d-43c8-a2e1-39086ac6f078'::text AS stop_code, 'Ministerstvo oborony'::text AS name_kk, 'Министерство обороны'::text AS name_ru, 'Ministerstvo oborony'::text AS name_en UNION ALL
  SELECT '17cc4828-7b49-4d27-bad3-8dce5b9803d4'::text AS stop_code, 'TRTs Keruen'::text AS name_kk, 'ТРЦ Керуен'::text AS name_ru, 'TRTs Keruen'::text AS name_en UNION ALL
  SELECT 'f10f105d-68d2-4a07-a64c-3570d19da0ff'::text AS stop_code, 'NK Kazmunaigaz'::text AS name_kk, 'НК Казмунаигаз'::text AS name_ru, 'NK Kazmunaigaz'::text AS name_en UNION ALL
  SELECT '3943eb59-f7df-4bc8-a03b-57ec0f53839b'::text AS stop_code, 'Sredniaia shkola No. 18'::text AS name_kk, 'Средниаиа школа № 18'::text AS name_ru, 'Sredniaia shkola No. 18'::text AS name_en UNION ALL
  SELECT 'b545b42e-bf63-4971-88da-0034cf57c6d3'::text AS stop_code, 'Sarybulak'::text AS name_kk, 'Сарыбулак'::text AS name_ru, 'Sarybulak'::text AS name_en UNION ALL
  SELECT '8be4569f-b109-4c67-aa6b-10e7e1ff0a1a'::text AS stop_code, 'prospekt Tlendieva'::text AS name_kk, 'проспект Тлендиева'::text AS name_ru, 'prospekt Tlendieva'::text AS name_en UNION ALL
  SELECT '1547f9fc-9cdb-4452-80b1-1de805d07791'::text AS stop_code, 'Akan Sery'::text AS name_kk, 'Акан Серы'::text AS name_ru, 'Akan Sery'::text AS name_en UNION ALL
  SELECT '2045b211-161c-475d-8e29-b5dcba8d5c88'::text AS stop_code, 'K''artaly'::text AS name_kk, 'Карталы'::text AS name_ru, 'K''artaly'::text AS name_en UNION ALL
  SELECT 'e26b277d-07e2-4a9a-8ac5-a8268eef6ddd'::text AS stop_code, 'Medeu'::text AS name_kk, 'Медеу'::text AS name_ru, 'Medeu'::text AS name_en UNION ALL
  SELECT '18e674ae-467c-4bf9-b5e9-6747a27c958b'::text AS stop_code, 'Kladbishche'::text AS name_kk, 'Кладбище'::text AS name_ru, 'Kladbishche'::text AS name_en UNION ALL
  SELECT '374a1eba-3bff-4242-854e-4043b5a0dd8c'::text AS stop_code, 'Shugyla'::text AS name_kk, 'шугыла'::text AS name_ru, 'Shugyla'::text AS name_en UNION ALL
  SELECT 'ddfa4130-2d84-47ca-9601-6141a4e1a792'::text AS stop_code, 'Titova'::text AS name_kk, 'Титова'::text AS name_ru, 'Titova'::text AS name_en UNION ALL
  SELECT '97f5041a-4317-40ea-ae45-e45b2bc1d54e'::text AS stop_code, 'Ardagerler'::text AS name_kk, 'Ардагерлер'::text AS name_ru, 'Ardagerler'::text AS name_en UNION ALL
  SELECT '980c8049-de1b-4b86-8f4a-c32728cb33d8'::text AS stop_code, 'Babataiuly'::text AS name_kk, 'Бабатаиулы'::text AS name_ru, 'Babataiuly'::text AS name_en UNION ALL
  SELECT '35cfa9fd-fcd4-49d3-98c5-2ee1aab26358'::text AS stop_code, 'per. Taitobe'::text AS name_kk, 'пер. Таитобе'::text AS name_ru, 'per. Taitobe'::text AS name_en UNION ALL
  SELECT '98026c8f-db24-493d-84e2-b5570fdf37d5'::text AS stop_code, 'Zhanakonys'::text AS name_kk, 'жанаконыс'::text AS name_ru, 'Zhanakonys'::text AS name_en UNION ALL
  SELECT '14c30498-4bf5-4b7c-84fb-3a8838e8f2e2'::text AS stop_code, 'Kafe Kazygurt'::text AS name_kk, 'Кафе Казыгурт'::text AS name_ru, 'Kafe Kazygurt'::text AS name_en UNION ALL
  SELECT 'b92ef832-a347-4211-9b54-0edf29047e57'::text AS stop_code, 'Gostinitsa Bakhyt'::text AS name_kk, 'Гостиница Бахыт'::text AS name_ru, 'Gostinitsa Bakhyt'::text AS name_en UNION ALL
  SELECT '887d0f28-1fde-47b7-88f4-2ceff1144fbf'::text AS stop_code, 'zh/m Koktal-2'::text AS name_kk, 'ж/м Коктал-2'::text AS name_ru, 'zh/m Koktal-2'::text AS name_en UNION ALL
  SELECT '6a6d9880-7a1a-4598-acba-a3408eef739e'::text AS stop_code, 'Tarbagatai'::text AS name_kk, 'Тарбагатаи'::text AS name_ru, 'Tarbagatai'::text AS name_en UNION ALL
  SELECT '66c67c6a-c5f7-4176-9d11-f2c8510ec6aa'::text AS stop_code, 'Mu''sa dukeni'::text AS name_kk, 'Муса дукени'::text AS name_ru, 'Mu''sa dukeni'::text AS name_en UNION ALL
  SELECT '220c90dc-c8e4-422b-98b5-d856f2eec1d1'::text AS stop_code, 'Nauryz48'::text AS name_kk, 'Наурыз48'::text AS name_ru, 'Nauryz48'::text AS name_en UNION ALL
  SELECT 'f4d06a9d-8db0-4730-b026-249312e0dbe5'::text AS stop_code, 'ulitsa Karasu'::text AS name_kk, 'улица Карасу'::text AS name_ru, 'ulitsa Karasu'::text AS name_en UNION ALL
  SELECT '24da8f75-2dc4-4a5d-becc-2898122eaae5'::text AS stop_code, 'Zh/d vokzal Astana 1'::text AS name_kk, 'ж/д вокзал Астана 1'::text AS name_ru, 'Zh/d vokzal Astana 1'::text AS name_en UNION ALL
  SELECT 'fe76afde-d448-4bbd-8aa5-7b753031d460'::text AS stop_code, 'Teatr Zhastar'::text AS name_kk, 'Театр жастар'::text AS name_ru, 'Teatr Zhastar'::text AS name_en UNION ALL
  SELECT '32457954-89fb-4c6d-8184-f67abcac80a8'::text AS stop_code, 'ul.Ybyrai Altynsarina'::text AS name_kk, 'ул.Ыбыраи Алтынсарина'::text AS name_ru, 'ul.Ybyrai Altynsarina'::text AS name_en UNION ALL
  SELECT '905e2f9c-80ce-4887-a0b1-44ad9636f3a6'::text AS stop_code, 'Ulitsa A. Moldagulovoi'::text AS name_kk, 'Улица А. Молдагуловои'::text AS name_ru, 'Ulitsa A. Moldagulovoi'::text AS name_en UNION ALL
  SELECT '731aaea7-faff-4e78-b247-ae0f180e0052'::text AS stop_code, 'Shkola-litsei No. 15'::text AS name_kk, 'школа-лицеи № 15'::text AS name_ru, 'Shkola-litsei No. 15'::text AS name_en UNION ALL
  SELECT '50768bd6-38ce-4f3d-943d-a11b456905d2'::text AS stop_code, 'Prospekt Saryarka'::text AS name_kk, 'Проспект Сарярка'::text AS name_ru, 'Prospekt Saryarka'::text AS name_en UNION ALL
  SELECT 'd46249b9-2884-4b23-be59-9e5f54f49c89'::text AS stop_code, 'Sportivnyi kompleks ABYROY'::text AS name_kk, 'Спортивныи комплекс АБЫРОЫ'::text AS name_ru, 'Sportivnyi kompleks ABYROY'::text AS name_en UNION ALL
  SELECT 'b2feffc5-c000-486c-9e55-99734f884cb0'::text AS stop_code, 'Shkola Zerde'::text AS name_kk, 'школа Зерде'::text AS name_ru, 'Shkola Zerde'::text AS name_en UNION ALL
  SELECT 'fe69c59f-7223-46c9-baf4-bc76f8e829ab'::text AS stop_code, 'Ulitsa Kenesary'::text AS name_kk, 'Улица Кенесары'::text AS name_ru, 'Ulitsa Kenesary'::text AS name_en UNION ALL
  SELECT '35914827-e837-47c4-93ce-d92d1d09d291'::text AS stop_code, 'Park Astana'::text AS name_kk, 'Парк Астана'::text AS name_ru, 'Park Astana'::text AS name_en UNION ALL
  SELECT '21a7b5b4-3e01-4457-91da-b8cc6ac14bbd'::text AS stop_code, 'TRTs KeruenCity'::text AS name_kk, 'ТРЦ КеруенКиты'::text AS name_ru, 'TRTs KeruenCity'::text AS name_en UNION ALL
  SELECT '01a3134a-4649-496d-b4fa-aea764a50a8b'::text AS stop_code, 'TRTs Saryarka'::text AS name_kk, 'ТРЦ Сарярка'::text AS name_ru, 'TRTs Saryarka'::text AS name_en UNION ALL
  SELECT '8f799508-4fac-4e5a-8fda-b24e19000780'::text AS stop_code, 'AO Kazmunaigaz'::text AS name_kk, 'АО Казмунаигаз'::text AS name_ru, 'AO Kazmunaigaz'::text AS name_en UNION ALL
  SELECT '160e90a6-0ebf-42f5-801d-bc26323a7705'::text AS stop_code, 'Ulitsa  Dinmukhameda Kunaeva'::text AS name_kk, 'Улица  Динмухамеда Кунаева'::text AS name_ru, 'Ulitsa  Dinmukhameda Kunaeva'::text AS name_en UNION ALL
  SELECT '6de59510-6e48-4efa-8459-b2c0d2766247'::text AS stop_code, 'Kazakhstan temir zholy'::text AS name_kk, 'Казахстан темир жолы'::text AS name_ru, 'Kazakhstan temir zholy'::text AS name_en UNION ALL
  SELECT '379d5591-eb02-45b1-b0b7-8407edfe55b4'::text AS stop_code, 'monument Baiterek'::text AS name_kk, 'монумент Баитерек'::text AS name_ru, 'monument Baiterek'::text AS name_en UNION ALL
  SELECT 'ec4e66cb-d30e-4e6a-9539-3051048f84da'::text AS stop_code, 'Dom Ministerstv'::text AS name_kk, 'Дом Министерств'::text AS name_ru, 'Dom Ministerstv'::text AS name_en UNION ALL
  SELECT '13c38731-1a07-40f0-a7ad-01c8539e2870'::text AS stop_code, 'Finansovyi tsentr'::text AS name_kk, 'Финансовыи центр'::text AS name_ru, 'Finansovyi tsentr'::text AS name_en UNION ALL
  SELECT '9e25e9c9-dd52-4436-ac0d-af6804369476'::text AS stop_code, 'ZhK Akzhaik'::text AS name_kk, 'ЖК Акжаик'::text AS name_ru, 'ZhK Akzhaik'::text AS name_en UNION ALL
  SELECT '6cb18f4c-19a8-4fce-9bd3-f4b918a13d8a'::text AS stop_code, 'K''arlyg''ash balabak''shasy'::text AS name_kk, 'Карлыгаш балабакшасы'::text AS name_ru, 'K''arlyg''ash balabak''shasy'::text AS name_en UNION ALL
  SELECT 'e9a3808a-45e7-4f39-9379-763d701979e7'::text AS stop_code, 'Triumfal''naia arka Mangilik El'::text AS name_kk, 'Триумфалнаиа арка Мангилик Ел'::text AS name_ru, 'Triumfal''naia arka Mangilik El'::text AS name_en UNION ALL
  SELECT 'daee5445-ae51-4bce-89ef-291e7c3b9ae0'::text AS stop_code, 'ul. Bukhar zhyrau'::text AS name_kk, 'ул. Бухар жырау'::text AS name_ru, 'ul. Bukhar zhyrau'::text AS name_en UNION ALL
  SELECT '98d1a5a7-9d18-4401-bc23-d018dc3e432d'::text AS stop_code, 'ZhK Promenad Ekspo'::text AS name_kk, 'ЖК Променад Експо'::text AS name_ru, 'ZhK Promenad Ekspo'::text AS name_en UNION ALL
  SELECT 'e80c5cc3-6d22-4bb2-8697-2c901ad33137'::text AS stop_code, 'ZhK Orynbor Towers'::text AS name_kk, 'ЖК Орынбор Товерс'::text AS name_ru, 'ZhK Orynbor Towers'::text AS name_en UNION ALL
  SELECT 'ad14c406-b8c8-49e6-8ed4-426612e851e7'::text AS stop_code, 'Astana EKSPO'::text AS name_kk, 'Астана ЕКСПО'::text AS name_ru, 'Astana EKSPO'::text AS name_en UNION ALL
  SELECT 'cb455c22-433c-415c-9dc6-4b38f567d97a'::text AS stop_code, 'ZhK Ekspo Siti'::text AS name_kk, 'ЖК Експо Сити'::text AS name_ru, 'ZhK Ekspo Siti'::text AS name_en UNION ALL
  SELECT 'd14ef85c-0e16-4e07-ba92-b1eef3a17499'::text AS stop_code, 'Bol''nitsa Meditsinskogo tsentra UDP RK'::text AS name_kk, 'Болница Медицинского центра УДП РК'::text AS name_ru, 'Bol''nitsa Meditsinskogo tsentra UDP RK'::text AS name_en UNION ALL
  SELECT '83e469fd-55cf-4299-8bb7-1307181ae453'::text AS stop_code, 'E 495'::text AS name_kk, 'Е 495'::text AS name_ru, 'E 495'::text AS name_en UNION ALL
  SELECT '024dc66b-2cc2-4c58-9482-caa7068d6eb2'::text AS stop_code, 'Detskii sad Karlygash'::text AS name_kk, 'Децкии сад Карлыгаш'::text AS name_ru, 'Detskii sad Karlygash'::text AS name_en UNION ALL
  SELECT '09b35dc0-2e95-4c03-b488-5eda1557f68b'::text AS stop_code, 'Ulitsa Birzhan sal'::text AS name_kk, 'Улица Биржан сал'::text AS name_ru, 'Ulitsa Birzhan sal'::text AS name_en UNION ALL
  SELECT 'd81e04ca-9213-4363-b2d1-34580954fc9e'::text AS stop_code, 'Ulitsa Il''iasa Esenberlina'::text AS name_kk, 'Улица Илиаса Есенберлина'::text AS name_ru, 'Ulitsa Il''iasa Esenberlina'::text AS name_en UNION ALL
  SELECT 'f61c6540-7d01-4563-a8a6-ef667d64ea20'::text AS stop_code, 'Agrotekhnicheskii universitet'::text AS name_kk, 'Агротехническии университет'::text AS name_ru, 'Agrotekhnicheskii universitet'::text AS name_en UNION ALL
  SELECT '4fddb84f-fb97-43b8-a619-e667607dc9de'::text AS stop_code, 'Meditsinskii universitet Astana'::text AS name_kk, 'Медицинскии университет Астана'::text AS name_ru, 'Meditsinskii universitet Astana'::text AS name_en UNION ALL
  SELECT '5ea2fd87-18be-448c-ba4a-011ed7449f1e'::text AS stop_code, 'Politekhnicheskii kolledzh'::text AS name_kk, 'Политехническии колледж'::text AS name_ru, 'Politekhnicheskii kolledzh'::text AS name_en UNION ALL
  SELECT '26d4ae3b-1b99-47f1-a819-0e4f77899d96'::text AS stop_code, 'ulitsa Karasu'::text AS name_kk, 'улица Карасу'::text AS name_ru, 'ulitsa Karasu'::text AS name_en UNION ALL
  SELECT 'fe9d6168-9e62-41bb-be9e-15853bdcfdfd'::text AS stop_code, 'Mu''sa dukeni'::text AS name_kk, 'Муса дукени'::text AS name_ru, 'Mu''sa dukeni'::text AS name_en UNION ALL
  SELECT '2dd9aae5-9429-4599-9e2b-19909c7551da'::text AS stop_code, 'Tarbagatai'::text AS name_kk, 'Тарбагатаи'::text AS name_ru, 'Tarbagatai'::text AS name_en UNION ALL
  SELECT '80f1899c-9a53-40c5-8e75-a2f6c1d74d82'::text AS stop_code, 'Aktobe'::text AS name_kk, 'Актобе'::text AS name_ru, 'Aktobe'::text AS name_en UNION ALL
  SELECT 'fe63a582-29bc-419b-8a03-5c1757b45e87'::text AS stop_code, 'Ulytau'::text AS name_kk, 'Улытау'::text AS name_ru, 'Ulytau'::text AS name_en UNION ALL
  SELECT '3c018a79-d48f-4d34-8f87-e5e6746013a9'::text AS stop_code, 'Gostinitsa Bakhyt'::text AS name_kk, 'Гостиница Бахыт'::text AS name_ru, 'Gostinitsa Bakhyt'::text AS name_en UNION ALL
  SELECT 'c901486e-6e2a-4bc5-a56b-ebe54673e704'::text AS stop_code, 'Keleshek'::text AS name_kk, 'Келешек'::text AS name_ru, 'Keleshek'::text AS name_en UNION ALL
  SELECT '2bbe99d3-1cdd-4707-af05-4d07edcfb875'::text AS stop_code, 'Zhanakonys'::text AS name_kk, 'жанаконыс'::text AS name_ru, 'Zhanakonys'::text AS name_en UNION ALL
  SELECT '88c76eb3-8629-453b-968f-d1aeaf15937f'::text AS stop_code, 'per. Taitobe'::text AS name_kk, 'пер. Таитобе'::text AS name_ru, 'per. Taitobe'::text AS name_en UNION ALL
  SELECT '519996b9-34d3-4260-942e-88b48ca22623'::text AS stop_code, 'Ardagerler'::text AS name_kk, 'Ардагерлер'::text AS name_ru, 'Ardagerler'::text AS name_en UNION ALL
  SELECT '2b2b7d9a-6879-45ea-9763-1fe18e018f2f'::text AS stop_code, 'Titova'::text AS name_kk, 'Титова'::text AS name_ru, 'Titova'::text AS name_en UNION ALL
  SELECT '64d084ee-3c50-4f86-a73b-39e127d3446f'::text AS stop_code, 'Shugyla'::text AS name_kk, 'шугыла'::text AS name_ru, 'Shugyla'::text AS name_en UNION ALL
  SELECT '9f845f42-9eac-4e28-8502-fc9922b6c923'::text AS stop_code, 'Astana EKSPO'::text AS name_kk, 'Астана ЕКСПО'::text AS name_ru, 'Astana EKSPO'::text AS name_en UNION ALL
  SELECT '1d53ab9f-c7f4-4aa4-b0f0-633962560cfa'::text AS stop_code, 'ZhK Orynbor Towers'::text AS name_kk, 'ЖК Орынбор Товерс'::text AS name_ru, 'ZhK Orynbor Towers'::text AS name_en UNION ALL
  SELECT '4ef6c8ac-8173-4c76-b194-918e3c3d876f'::text AS stop_code, 'ZhK Promenad Ekspo'::text AS name_kk, 'ЖК Променад Експо'::text AS name_ru, 'ZhK Promenad Ekspo'::text AS name_en UNION ALL
  SELECT '93f2e175-bd6e-43d4-8498-a0b68fa24560'::text AS stop_code, 'UDP'::text AS name_kk, 'УДП'::text AS name_ru, 'UDP'::text AS name_en UNION ALL
  SELECT '4efbf1dc-b4dc-46a4-9f0b-70f8d73ff6b2'::text AS stop_code, 'Bukhar zhyrau'::text AS name_kk, 'Бухар жырау'::text AS name_ru, 'Bukhar zhyrau'::text AS name_en UNION ALL
  SELECT '9230cadb-e2b9-4939-8b6f-8be6d9da92c8'::text AS stop_code, 'Triumfal''naia arka Mangilik El'::text AS name_kk, 'Триумфалнаиа арка Мангилик Ел'::text AS name_ru, 'Triumfal''naia arka Mangilik El'::text AS name_en UNION ALL
  SELECT '1552b0e1-bb57-49dc-b4cb-557a39df06b4'::text AS stop_code, 'K''arlyg''ash balabak''shasy'::text AS name_kk, 'Карлыгаш балабакшасы'::text AS name_ru, 'K''arlyg''ash balabak''shasy'::text AS name_en UNION ALL
  SELECT 'f5fa8abd-4d11-4331-9424-0c9638a34de4'::text AS stop_code, 'ZhK Akzhaik'::text AS name_kk, 'ЖК Акжаик'::text AS name_ru, 'ZhK Akzhaik'::text AS name_en UNION ALL
  SELECT 'f3a7aefe-7c9f-4391-8091-7df545584ac0'::text AS stop_code, 'Finansovyi tsentr'::text AS name_kk, 'Финансовыи центр'::text AS name_ru, 'Finansovyi tsentr'::text AS name_en UNION ALL
  SELECT 'ffe7ac12-5298-4f2b-83e5-894509a544ed'::text AS stop_code, 'K''azak''kontsert im. Rozy Baglanovoi'::text AS name_kk, 'Казакконцерт им. Розы Баглановои'::text AS name_ru, 'K''azak''kontsert im. Rozy Baglanovoi'::text AS name_en UNION ALL
  SELECT '2ca9397c-8bbe-40c0-9a6d-545216696cfe'::text AS stop_code, 'Dom ministerstv'::text AS name_kk, 'Дом министерств'::text AS name_ru, 'Dom ministerstv'::text AS name_en UNION ALL
  SELECT '06232fac-a185-48c0-8ac7-70a493306087'::text AS stop_code, 'Kazakhstan temir zholy'::text AS name_kk, 'Казахстан темир жолы'::text AS name_ru, 'Kazakhstan temir zholy'::text AS name_en UNION ALL
  SELECT 'e9dc4756-2990-4fa3-a0b8-a04d6312f913'::text AS stop_code, 'Ulitsa  Dinmukhameda Kunaeva'::text AS name_kk, 'Улица  Динмухамеда Кунаева'::text AS name_ru, 'Ulitsa  Dinmukhameda Kunaeva'::text AS name_en UNION ALL
  SELECT 'f4570762-f53c-463c-89a4-87f4e916d5a3'::text AS stop_code, 'TRTs Khan Shatyr'::text AS name_kk, 'ТРЦ хан шатыр'::text AS name_ru, 'TRTs Khan Shatyr'::text AS name_en UNION ALL
  SELECT '1100a1f5-0017-4d32-a284-74289da87c19'::text AS stop_code, 'Teatr Astana Opera'::text AS name_kk, 'Театр Астана Опера'::text AS name_ru, 'Teatr Astana Opera'::text AS name_en UNION ALL
  SELECT 'b199b336-fc58-47ca-bf2e-34f180c3c111'::text AS stop_code, 'TRTs Saryarka'::text AS name_kk, 'ТРЦ Сарярка'::text AS name_ru, 'TRTs Saryarka'::text AS name_en UNION ALL
  SELECT '666cc2b2-73dc-4d32-afd1-1ce0b6280dd8'::text AS stop_code, 'TRTs KeruenCity'::text AS name_kk, 'ТРЦ КеруенКиты'::text AS name_ru, 'TRTs KeruenCity'::text AS name_en UNION ALL
  SELECT 'da885f37-5bc2-43d5-b95c-ef82447df886'::text AS stop_code, 'Korgalzhinskaia trassa'::text AS name_kk, 'Коргалжинскаиа трасса'::text AS name_ru, 'Korgalzhinskaia trassa'::text AS name_en UNION ALL
  SELECT '3f01777a-d987-4808-83e3-80e0193ebb62'::text AS stop_code, 'Park Astana'::text AS name_kk, 'Парк Астана'::text AS name_ru, 'Park Astana'::text AS name_en UNION ALL
  SELECT 'edf55deb-81ff-41ae-bec5-a5a7b2cf5230'::text AS stop_code, 'Ulitsa Kenesary'::text AS name_kk, 'Улица Кенесары'::text AS name_ru, 'Ulitsa Kenesary'::text AS name_en UNION ALL
  SELECT '6aba57b3-2ccf-46aa-a877-7302fe66740e'::text AS stop_code, 'Shkola Zerde'::text AS name_kk, 'школа Зерде'::text AS name_ru, 'Shkola Zerde'::text AS name_en UNION ALL
  SELECT '4cc233c3-db14-4e65-b96b-91271c045f99'::text AS stop_code, 'Sportivnyi kompleks ABYROY'::text AS name_kk, 'Спортивныи комплекс АБЫРОЫ'::text AS name_ru, 'Sportivnyi kompleks ABYROY'::text AS name_en UNION ALL
  SELECT 'ce8054ef-6b41-439f-b763-a770a69cf95d'::text AS stop_code, 'Prospekt Saryarka'::text AS name_kk, 'Проспект Сарярка'::text AS name_ru, 'Prospekt Saryarka'::text AS name_en UNION ALL
  SELECT '3d570ad2-db12-47d1-b15e-a33dfa403c56'::text AS stop_code, 'TD Koktem'::text AS name_kk, 'ТД Коктем'::text AS name_ru, 'TD Koktem'::text AS name_en UNION ALL
  SELECT '9c39bef4-78ba-41cc-af86-4e9cec3e06dd'::text AS stop_code, 'Shkola-litsei No. 15'::text AS name_kk, 'школа-лицеи № 15'::text AS name_ru, 'Shkola-litsei No. 15'::text AS name_en UNION ALL
  SELECT '15829acf-630a-4f13-9472-b6f8a679e0a8'::text AS stop_code, 'Ulitsa Moskovskaia'::text AS name_kk, 'Улица Московскаиа'::text AS name_ru, 'Ulitsa Moskovskaia'::text AS name_en UNION ALL
  SELECT 'df129513-5202-4119-963f-1090546d183d'::text AS stop_code, 'Ulitsa A. Moldagulovoi'::text AS name_kk, 'Улица А. Молдагуловои'::text AS name_ru, 'Ulitsa A. Moldagulovoi'::text AS name_en UNION ALL
  SELECT '0dfeaf23-1068-4a93-9666-5cc804d389a1'::text AS stop_code, 'Teatr Zhastar'::text AS name_kk, 'Театр жастар'::text AS name_ru, 'Teatr Zhastar'::text AS name_en UNION ALL
  SELECT 'e6719284-431b-4c10-bb30-4f2e99de2f98'::text AS stop_code, 'TD Daulet'::text AS name_kk, 'ТД Даулет'::text AS name_ru, 'TD Daulet'::text AS name_en UNION ALL
  SELECT '63220f3a-eeb2-41ce-9cae-7157668360e9'::text AS stop_code, 'Zh/d vokzal Astana 1'::text AS name_kk, 'ж/д вокзал Астана 1'::text AS name_ru, 'Zh/d vokzal Astana 1'::text AS name_en UNION ALL
  SELECT '3e758949-78d7-4c07-b00b-e81d572481ee'::text AS stop_code, 'Kanal Nura-Esil'''::text AS name_kk, 'Канал Нура-Есил'::text AS name_ru, 'Kanal Nura-Esil'''::text AS name_en UNION ALL
  SELECT '13a79ef8-965a-440a-be79-13f1aa3b7e6f'::text AS stop_code, 'zh/m Prigorodnyi'::text AS name_kk, 'ж/м Пригородныи'::text AS name_ru, 'zh/m Prigorodnyi'::text AS name_en UNION ALL
  SELECT '1617c71a-0c29-4ad2-b1b4-5ea952e80f75'::text AS stop_code, 'zh/m Prigorodnyi'::text AS name_kk, 'ж/м Пригородныи'::text AS name_ru, 'zh/m Prigorodnyi'::text AS name_en UNION ALL
  SELECT '4614db92-63be-4042-bc5a-4f82ce5d47fe'::text AS stop_code, 'Kanal Nura-Esil'''::text AS name_kk, 'Канал Нура-Есил'::text AS name_ru, 'Kanal Nura-Esil'''::text AS name_en UNION ALL
  SELECT 'bc3e6bd7-08c3-470f-9c82-e483399884de'::text AS stop_code, 'ZhK Family Park'::text AS name_kk, 'ЖК Фамилы Парк'::text AS name_ru, 'ZhK Family Park'::text AS name_en UNION ALL
  SELECT 'bf5784b8-65f2-46b7-824e-78e29e38f3d1'::text AS stop_code, 'Karkaralinskoe shosse'::text AS name_kk, 'Каркаралинское шоссе'::text AS name_ru, 'Karkaralinskoe shosse'::text AS name_en UNION ALL
  SELECT '0a75a06f-8e5d-48f2-ac85-8211908d4c41'::text AS stop_code, 'Stella Zvezda Astany'::text AS name_kk, 'Стелла Звезда Астаны'::text AS name_ru, 'Stella Zvezda Astany'::text AS name_en UNION ALL
  SELECT 'a57b56fd-5f03-4ce5-bbef-6bcc23035352'::text AS stop_code, 'Tsentral''nyi gospital'''::text AS name_kk, 'централныи госпитал'::text AS name_ru, 'Tsentral''nyi gospital'''::text AS name_en UNION ALL
  SELECT 'ccd5e97f-c483-4209-96d7-8d64466fdc26'::text AS stop_code, 'Nazarbaev universitet'::text AS name_kk, 'Назарбаев университет'::text AS name_ru, 'Nazarbaev universitet'::text AS name_en UNION ALL
  SELECT '0354d63f-65ad-4bef-b2e1-b79439bb9f31'::text AS stop_code, 'ZhK Ekspo-Plaza'::text AS name_kk, 'ЖК Експо-Плаза'::text AS name_ru, 'ZhK Ekspo-Plaza'::text AS name_en UNION ALL
  SELECT '068882a1-be66-4fce-b012-98a2dd51acc8'::text AS stop_code, 'Ledovyi dvorets Alau'::text AS name_kk, 'Ледовыи дворец Алау'::text AS name_ru, 'Ledovyi dvorets Alau'::text AS name_en UNION ALL
  SELECT '609457bf-32ed-4cae-8bc4-56c755311af4'::text AS stop_code, 'Stadion Astana-Arena'::text AS name_kk, 'Стадион Астана-Арена'::text AS name_ru, 'Stadion Astana-Arena'::text AS name_en UNION ALL
  SELECT 'c3484f80-419a-4ea3-9355-c33104abab7e'::text AS stop_code, 'E 319'::text AS name_kk, 'Е 319'::text AS name_ru, 'E 319'::text AS name_en UNION ALL
  SELECT '4b830103-8b6e-4273-aedc-b4ca2c34dda8'::text AS stop_code, 'Kanal Nura-Esil'''::text AS name_kk, 'Канал Нура-Есил'::text AS name_ru, 'Kanal Nura-Esil'''::text AS name_en UNION ALL
  SELECT 'bc1ee4e3-ab3a-4b4f-81cd-46eba42d01df'::text AS stop_code, 'Sadovodcheskoe obshchestvo Aviator'::text AS name_kk, 'Садоводческое общество Авиатор'::text AS name_ru, 'Sadovodcheskoe obshchestvo Aviator'::text AS name_en UNION ALL
  SELECT 'b27e4484-f45f-490f-b75f-d3c0c5f01eba'::text AS stop_code, 'ul. Zhanadariia'::text AS name_kk, 'ул. жанадарииа'::text AS name_ru, 'ul. Zhanadariia'::text AS name_en UNION ALL
  SELECT '953d5019-5468-4971-8712-6648eda53cfe'::text AS stop_code, 'Detskii sad Balbulak'::text AS name_kk, 'Децкии сад Балбулак'::text AS name_ru, 'Detskii sad Balbulak'::text AS name_en UNION ALL
  SELECT '0116b4d3-b09f-4091-8e8d-3363907905fa'::text AS stop_code, 'Sarytogai'::text AS name_kk, 'Сарытогаи'::text AS name_ru, 'Sarytogai'::text AS name_en UNION ALL
  SELECT '9ee1bf93-fd79-4c3c-a63c-dae21572b98a'::text AS stop_code, 'sredniaia shkola No. 24'::text AS name_kk, 'средниаиа школа № 24'::text AS name_ru, 'sredniaia shkola No. 24'::text AS name_en UNION ALL
  SELECT '28407e90-671f-482f-95f4-c692dd4d1e90'::text AS stop_code, 'Ulitsa Arnasai'::text AS name_kk, 'Улица Арнасаи'::text AS name_ru, 'Ulitsa Arnasai'::text AS name_en UNION ALL
  SELECT 'b42cb534-1201-4a4d-9b60-3774280e24fa'::text AS stop_code, 'Mechet'' Al''zhan Ana'::text AS name_kk, 'Мечет Алжан Ана'::text AS name_ru, 'Mechet'' Al''zhan Ana'::text AS name_en UNION ALL
  SELECT '5dafe705-9a04-4727-a75e-7ed2195cfe2a'::text AS stop_code, 'Mezhdunarodnyi aeroport'::text AS name_kk, 'Международныи аеропорт'::text AS name_ru, 'Mezhdunarodnyi aeroport'::text AS name_en UNION ALL
  SELECT '0efb91bb-82ba-4082-a5d9-69e392b7510f'::text AS stop_code, 'Mezhdunarodnyi aeroport'::text AS name_kk, 'Международныи аеропорт'::text AS name_ru, 'Mezhdunarodnyi aeroport'::text AS name_en UNION ALL
  SELECT 'eb69b78a-a836-40b3-8ca7-a7b8aaed7ec6'::text AS stop_code, 'Mechet'' Al''zhan Ana'::text AS name_kk, 'Мечет Алжан Ана'::text AS name_ru, 'Mechet'' Al''zhan Ana'::text AS name_en UNION ALL
  SELECT '19d56c0b-6421-4f46-8ec3-2781ee8b93ec'::text AS stop_code, 'Ulitsa Arnasai'::text AS name_kk, 'Улица Арнасаи'::text AS name_ru, 'Ulitsa Arnasai'::text AS name_en UNION ALL
  SELECT '83a76452-75bb-411e-851e-9e07da361031'::text AS stop_code, 'sredniaia shkola No. 24'::text AS name_kk, 'средниаиа школа № 24'::text AS name_ru, 'sredniaia shkola No. 24'::text AS name_en UNION ALL
  SELECT '28764497-a568-434f-83dd-932a3c91e199'::text AS stop_code, 'Sarytogai'::text AS name_kk, 'Сарытогаи'::text AS name_ru, 'Sarytogai'::text AS name_en UNION ALL
  SELECT 'a4e48b15-9424-41b4-92a1-8331bbdd6863'::text AS stop_code, 'Detskii sad Balbulak'::text AS name_kk, 'Децкии сад Балбулак'::text AS name_ru, 'Detskii sad Balbulak'::text AS name_en UNION ALL
  SELECT '88b7ca3b-3501-4efe-b33f-701453ffa277'::text AS stop_code, 'ul. Zhanadariia'::text AS name_kk, 'ул. жанадарииа'::text AS name_ru, 'ul. Zhanadariia'::text AS name_en UNION ALL
  SELECT '54623320-dd0b-452c-9ee8-9cf89671b8b0'::text AS stop_code, 'ZhK Aq-Jol'::text AS name_kk, 'ЖК Ак-Йол'::text AS name_ru, 'ZhK Aq-Jol'::text AS name_en UNION ALL
  SELECT 'a6d09382-75f3-4706-85e8-2a5b775af30c'::text AS stop_code, 'Sadovodcheskoe obshchestvo Aviator'::text AS name_kk, 'Садоводческое общество Авиатор'::text AS name_ru, 'Sadovodcheskoe obshchestvo Aviator'::text AS name_en UNION ALL
  SELECT 'ea8a20e2-6aea-407c-b42b-f9c55439718b'::text AS stop_code, 'Kanal Nura-Esil'''::text AS name_kk, 'Канал Нура-Есил'::text AS name_ru, 'Kanal Nura-Esil'''::text AS name_en UNION ALL
  SELECT 'fc4e269d-3cc0-46fd-87b7-4ae1ac9e2361'::text AS stop_code, 'E 319'::text AS name_kk, 'Е 319'::text AS name_ru, 'E 319'::text AS name_en UNION ALL
  SELECT 'a78b2c1d-ec83-4c0d-90b1-97d4136ebaae'::text AS stop_code, 'Detskii sad Karlygash-2'::text AS name_kk, 'Децкии сад Карлыгаш-2'::text AS name_ru, 'Detskii sad Karlygash-2'::text AS name_en UNION ALL
  SELECT 'ddc8cb38-d19d-43a5-8f21-eb761485ed15'::text AS stop_code, 'Bol''nitsa Meditsinskogo tsentra UDP RK'::text AS name_kk, 'Болница Медицинского центра УДП РК'::text AS name_ru, 'Bol''nitsa Meditsinskogo tsentra UDP RK'::text AS name_en UNION ALL
  SELECT 'ef859046-109a-4362-9339-ca295f511796'::text AS stop_code, 'ZhK Ekspo Siti'::text AS name_kk, 'ЖК Експо Сити'::text AS name_ru, 'ZhK Ekspo Siti'::text AS name_en UNION ALL
  SELECT '90bbca78-c461-4348-9ec8-4911c68a3ae3'::text AS stop_code, 'Biznes tsentr Marden'::text AS name_kk, 'Бизнес центр Марден'::text AS name_ru, 'Biznes tsentr Marden'::text AS name_en UNION ALL
  SELECT '639393f6-22fb-4ab6-a13d-98f9131736b2'::text AS stop_code, 'Narodnyi bank'::text AS name_kk, 'Народныи банк'::text AS name_ru, 'Narodnyi bank'::text AS name_en UNION ALL
  SELECT 'e0edfbd5-454b-49aa-bd3f-9f55d679c2a4'::text AS stop_code, 'Ulitsa Amangel''dy Imanova'::text AS name_kk, 'Улица Амангелды Иманова'::text AS name_ru, 'Ulitsa Amangel''dy Imanova'::text AS name_en UNION ALL
  SELECT '3abac3ba-87c0-480c-aa39-fc3ec081e9c6'::text AS stop_code, 'Zhanibek Tarkhana'::text AS name_kk, 'жанибек Тархана'::text AS name_ru, 'Zhanibek Tarkhana'::text AS name_en UNION ALL
  SELECT '4aed197d-2627-48aa-9191-4b45ed52ddbb'::text AS stop_code, 'Mikroraion Samal'::text AS name_kk, 'Микрораион Самал'::text AS name_ru, 'Mikroraion Samal'::text AS name_en UNION ALL
  SELECT 'f86c97bc-80c0-4a7e-bbc0-4dbff06148ab'::text AS stop_code, 'Park Atatiurk'::text AS name_kk, 'Парк Ататиурк'::text AS name_ru, 'Park Atatiurk'::text AS name_en UNION ALL
  SELECT '7e094e15-7fe2-424d-be5d-c650a7eaac09'::text AS stop_code, 'Ulitsa Amman'::text AS name_kk, 'Улица Амман'::text AS name_ru, 'Ulitsa Amman'::text AS name_en UNION ALL
  SELECT '0c611096-98ec-4284-85e1-68523f4436d3'::text AS stop_code, 'Dom ministerstv'::text AS name_kk, 'Дом министерств'::text AS name_ru, 'Dom ministerstv'::text AS name_en UNION ALL
  SELECT 'cac60a34-335b-43a0-aeb1-8d57a154facc'::text AS stop_code, 'Kardiokhirurgicheskaia klinika'::text AS name_kk, 'Кардиохирургическаиа клиника'::text AS name_ru, 'Kardiokhirurgicheskaia klinika'::text AS name_en UNION ALL
  SELECT 'bf58aae9-f17c-4eb5-b280-bd59ef34e7d4'::text AS stop_code, 'Tsentr neirokhirurgii'::text AS name_kk, 'центр неирохирургии'::text AS name_ru, 'Tsentr neirokhirurgii'::text AS name_en UNION ALL
  SELECT 'edca5c3c-a4bf-4aad-b25a-fa60e056cb86'::text AS stop_code, 'Biznes tsentr Asyl-Tau'::text AS name_kk, 'Бизнес центр Асыл-Тау'::text AS name_ru, 'Biznes tsentr Asyl-Tau'::text AS name_en UNION ALL
  SELECT 'c885bb33-9730-4071-9429-8ad8e56f4a7e'::text AS stop_code, 'Dvorets edinoborstv im. Zhaksylyka Ushkempirova'::text AS name_kk, 'Дворец единоборств им. жаксылыка Ушкемпирова'::text AS name_ru, 'Dvorets edinoborstv im. Zhaksylyka Ushkempirova'::text AS name_en UNION ALL
  SELECT '25160f65-5b76-42df-8126-ba7e0dca32d0'::text AS stop_code, 'Stadion Astana-Arena'::text AS name_kk, 'Стадион Астана-Арена'::text AS name_ru, 'Stadion Astana-Arena'::text AS name_en UNION ALL
  SELECT '8d5505db-a9f3-4d54-9b9e-bfd7f6e60265'::text AS stop_code, 'Ledovyi dvorets Alau'::text AS name_kk, 'Ледовыи дворец Алау'::text AS name_ru, 'Ledovyi dvorets Alau'::text AS name_en UNION ALL
  SELECT 'ad8964a3-38aa-4ec7-be27-55d4fa8437de'::text AS stop_code, 'ZhK Ekspo-Plaza'::text AS name_kk, 'ЖК Експо-Плаза'::text AS name_ru, 'ZhK Ekspo-Plaza'::text AS name_en UNION ALL
  SELECT '12cabd75-d75d-4b82-8364-770c7812d47f'::text AS stop_code, 'Nazarbaev universitet'::text AS name_kk, 'Назарбаев университет'::text AS name_ru, 'Nazarbaev universitet'::text AS name_en UNION ALL
  SELECT 'a63cf9b0-b800-4694-9701-ff96efc9a37d'::text AS stop_code, 'Tsentral''nyi gospital'''::text AS name_kk, 'централныи госпитал'::text AS name_ru, 'Tsentral''nyi gospital'''::text AS name_en UNION ALL
  SELECT '97fe4589-8e42-4006-b28b-a0fdb7f06199'::text AS stop_code, 'ZhK Budapesht'::text AS name_kk, 'ЖК Будапешт'::text AS name_ru, 'ZhK Budapesht'::text AS name_en UNION ALL
  SELECT '06eee664-f6eb-43f7-ac6a-de0d6e693a27'::text AS stop_code, 'Stela Zvezda Astany'::text AS name_kk, 'Стела Звезда Астаны'::text AS name_ru, 'Stela Zvezda Astany'::text AS name_en UNION ALL
  SELECT '04fd1fc3-b800-465a-be89-5367e0313d21'::text AS stop_code, 'Karkaralinskoe shosse'::text AS name_kk, 'Каркаралинское шоссе'::text AS name_ru, 'Karkaralinskoe shosse'::text AS name_en UNION ALL
  SELECT 'ccf9d9ab-2a88-4d8f-aa7d-4d3b7eaf7a50'::text AS stop_code, 'ZhK Family Park'::text AS name_kk, 'ЖК Фамилы Парк'::text AS name_ru, 'ZhK Family Park'::text AS name_en UNION ALL
  SELECT 'cb981230-114b-4e6e-97a2-9234afcc4418'::text AS stop_code, 'Dvorets edinoborstv'::text AS name_kk, 'Дворец единоборств'::text AS name_ru, 'Dvorets edinoborstv'::text AS name_en UNION ALL
  SELECT 'd59b3173-0b00-4498-8684-00131374163c'::text AS stop_code, 'Biznes tsentr Asyl-Tau'::text AS name_kk, 'Бизнес центр Асыл-Тау'::text AS name_ru, 'Biznes tsentr Asyl-Tau'::text AS name_en UNION ALL
  SELECT 'af31f517-9fae-414c-918f-82aba623f587'::text AS stop_code, 'Tsentr neirokhirurgii'::text AS name_kk, 'центр неирохирургии'::text AS name_ru, 'Tsentr neirokhirurgii'::text AS name_en UNION ALL
  SELECT '68738775-8984-47fb-a284-7b3a3e2a54cf'::text AS stop_code, 'Ulitsa  Dinmukhameda Kunaeva'::text AS name_kk, 'Улица  Динмухамеда Кунаева'::text AS name_ru, 'Ulitsa  Dinmukhameda Kunaeva'::text AS name_en UNION ALL
  SELECT '542282bd-62d3-4c68-8246-e81186171837'::text AS stop_code, 'Kazakhstan temir zholy'::text AS name_kk, 'Казахстан темир жолы'::text AS name_ru, 'Kazakhstan temir zholy'::text AS name_en UNION ALL
  SELECT '1cebd4f9-b4db-4bed-8f51-5a5b7f3ab5e3'::text AS stop_code, 'ZhK Milanskii kvartal'::text AS name_kk, 'ЖК Миланскии квартал'::text AS name_ru, 'ZhK Milanskii kvartal'::text AS name_en UNION ALL
  SELECT 'd32c99c4-e064-4c62-a74e-fdfd54f9341c'::text AS stop_code, 'Ulitsa Zhumabeka Tashenova'::text AS name_kk, 'Улица жумабека Ташенова'::text AS name_ru, 'Ulitsa Zhumabeka Tashenova'::text AS name_en UNION ALL
  SELECT 'e0b23f68-0123-40e5-ac0d-71b4af6b7274'::text AS stop_code, 'Ulitsa Amman'::text AS name_kk, 'Улица Амман'::text AS name_ru, 'Ulitsa Amman'::text AS name_en UNION ALL
  SELECT 'acabcf72-2a19-4891-979d-01cbd346878d'::text AS stop_code, 'Park Atatiurk'::text AS name_kk, 'Парк Ататиурк'::text AS name_ru, 'Park Atatiurk'::text AS name_en UNION ALL
  SELECT '527f6d97-4b07-45e8-b2d8-794dbc40075b'::text AS stop_code, 'Mikroraion Samal'::text AS name_kk, 'Микрораион Самал'::text AS name_ru, 'Mikroraion Samal'::text AS name_en UNION ALL
  SELECT 'd78e223c-3a67-42db-91eb-12858d261cb0'::text AS stop_code, 'Ulitsa Amangel''dy Imanova'::text AS name_kk, 'Улица Амангелды Иманова'::text AS name_ru, 'Ulitsa Amangel''dy Imanova'::text AS name_en UNION ALL
  SELECT '27123abe-5a4f-4116-b048-4e2d32d8a104'::text AS stop_code, 'Narodnyi bank'::text AS name_kk, 'Народныи банк'::text AS name_ru, 'Narodnyi bank'::text AS name_en UNION ALL
  SELECT 'fe106f1e-bc78-493a-a353-8ec1b0ab30aa'::text AS stop_code, 'Biznes tsentr Marden'::text AS name_kk, 'Бизнес центр Марден'::text AS name_ru, 'Biznes tsentr Marden'::text AS name_en UNION ALL
  SELECT 'c07d5a37-7945-403c-83a0-a6a84c87944c'::text AS stop_code, 'Alibi Zhangel''dina'::text AS name_kk, 'Алиби жангелдина'::text AS name_ru, 'Alibi Zhangel''dina'::text AS name_en UNION ALL
  SELECT '180c6cec-9a94-4a62-a902-168555638d9c'::text AS stop_code, 'Politekhnicheskii kolledzh'::text AS name_kk, 'Политехническии колледж'::text AS name_ru, 'Politekhnicheskii kolledzh'::text AS name_en UNION ALL
  SELECT 'de17c14c-a026-47c4-9c55-d1729bf48ce6'::text AS stop_code, 'Meditsinskii universitet Astana'::text AS name_kk, 'Медицинскии университет Астана'::text AS name_ru, 'Meditsinskii universitet Astana'::text AS name_en UNION ALL
  SELECT '782c5de3-4a10-4129-9dfb-8f19e6c95a25'::text AS stop_code, 'Agrotekhnicheskii universitet'::text AS name_kk, 'Агротехническии университет'::text AS name_ru, 'Agrotekhnicheskii universitet'::text AS name_en UNION ALL
  SELECT '04530e5f-9e64-4ae3-a962-589640451d45'::text AS stop_code, 'Il''iasa Esenberlina'::text AS name_kk, 'Илиаса Есенберлина'::text AS name_ru, 'Il''iasa Esenberlina'::text AS name_en UNION ALL
  SELECT '6b2eda8b-de4f-4bae-b178-d19e439922d7'::text AS stop_code, 'Ulitsa Birzhan sal'::text AS name_kk, 'Улица Биржан сал'::text AS name_ru, 'Ulitsa Birzhan sal'::text AS name_en UNION ALL
  SELECT '623fcc14-2417-4d31-84b9-ec08483a12ea'::text AS stop_code, 'TD Daulet'::text AS name_kk, 'ТД Даулет'::text AS name_ru, 'TD Daulet'::text AS name_en
) AS v
WHERE bs.stop_code = v.stop_code;

COMMIT;
